// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://sadewa.framer.website/
// Generated: 2026-06-15T07:18:57.924Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#0000ee' | '#131313' | '#f3f3f3' | '#ffffff' | '#797979' | '#98fe00' | '#d3d3d3' | '#e5e5e5' | '#3a3a3a' | '#ff9500' | '#de362a' | '#b4b4b4' | '#999999';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Satoshi' | 'Roboto Mono' | 'Times New Roman' | 'Geist' | 'Inter';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '700' | '600';

export type SpacingToken = '1px' | '30px' | '40px' | '48px' | '56px' | '64px' | '70px' | '80px' | '100px' | '110px' | '130px' | '140px' | '150px' | '160px' | '170px';

export type RadiusToken = '1px' | '4px' | '10px' | '14px' | '50px' | '64px' | '1000px';

export type DurationToken = '200ms' | '400ms' | '1000ms' | '1900ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
