// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://calisto.framer.website/
// Generated: 2026-06-15T07:16:59.709Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#0000ee' | '#255ccc' | '#666666' | '#0d0d0d' | '#ffffff' | '#f5f5f5' | '#1c1c1c' | '#525252' | '#308dff' | '#59afff' | '#767676' | '#d9d9d9';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Manrope' | 'Times New Roman' | 'Inter' | 'Inter Tight';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600' | '700';

export type SpacingToken = '1px' | '24px' | '30px' | '40px' | '48px' | '52px' | '80px' | '100px' | '120px' | '160px';

export type RadiusToken = '4px' | '8px' | '11px' | '14px' | '20px' | '23px' | '27px' | '30px' | '38px' | '50px' | '100px';

export type DurationToken = '200ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
