// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://agent.framer.wiki/
// Generated: 2026-06-15T07:08:10.202Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#0000ee' | '#ffffff' | '#9ba5b5' | '#4e5b6d' | '#37ea9e' | '#042018' | '#16a781' | '#273241' | '#e9ebef' | '#107a5e' | '#6aebc9' | '#d1d5dd' | '#82dbf7' | '#95f4cc' | '#1a1d21' | '#9b9c9e' | '#1cd3a3' | '#a6b0f2' | '#0a4d3b' | '#0c1132' | '#686b6e' | '#4ac97e' | '#101010' | '#333333' | '#bbbbbb';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Geist' | 'Times New Roman' | 'Inter' | 'Plus Jakarta Sans';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600' | '700';

export type SpacingToken = '1px' | '20px' | '24px' | '30px' | '36px' | '40px' | '48px' | '64px' | '80px' | '88px' | '96px';

export type RadiusToken = '3px' | '6px' | '10px' | '16px' | '20px' | '24px' | '30px' | '90px' | '100px' | '1000px';

export type DurationToken = '100ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
