// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://orbai-template.framer.website/
// Generated: 2026-06-15T07:15:14.866Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary';
export type ColorHex  = '#000000' | '#0000ee' | '#f5f5f5' | '#ffffff';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter' | 'Satoshi' | 'Times New Roman';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '700' | '600';

export type SpacingToken = '4px' | '20px' | '24px' | '30px' | '40px' | '44px' | '60px' | '80px' | '100px' | '160px' | '200px';

export type RadiusToken = '5px' | '8px' | '11px' | '14px' | '20px' | '23px' | '34px' | '40px' | '50px' | '60px' | '100px' | '192px' | '228px' | '455px' | '1000px';

export type DurationToken = never;
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
