// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://aithor.framer.website/
// Generated: 2026-06-15T07:12:44.561Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary';
export type ColorHex  = '#000000' | '#0000ee' | '#4f4f4f' | '#0a0a0a' | '#f0f0f0' | '#ff3700' | '#e5e5e5' | '#ffffff' | '#767676' | '#151619' | '#a1a1a1';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Geist' | 'Halant' | 'Times New Roman' | 'Outfit' | 'Switzer' | 'Inter' | 'Fragment Mono';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '500' | '700';

export type SpacingToken = '1px' | '10px' | '18px' | '24px' | '30px' | '40px' | '50px' | '55px' | '60px' | '80px' | '100px' | '140px' | '150px' | '160px' | '180px' | '200px';

export type RadiusToken = '3px' | '7px' | '10px' | '13px' | '16px' | '20px' | '30px' | '50px';

export type DurationToken = '1ms' | '200ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
